name: Project Automations
on:
  issues:
    types:
      - opened
      - reopened
      - closed
      - labeled
  pull_request:
    types:
      - opened

env:
  ice_box: ğŸ§Š Ice Box
  new: ğŸ†• New
  ready: ğŸ”– Ready
  on_deck: ğŸ“¨ On Deck
  todo: ğŸ“‹ To Do
  in_progress: ğŸ— In progress
  in_review: ğŸ‘€ In review
  done: âœ… Done

jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move issue to ${{ env.new }}
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.CANVAS_BOARD_TOKEN }}
          organization: Workday
          project_id: 4
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.new }}
  issue_closed:
    name: issue_closed
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'closed'
    steps:
      - name: Moved issue to ${{ env.done }}
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.CANVAS_BOARD_TOKEN }}
          organization: Workday
          project_id: 4
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.done }}
  issue_labeled:
    name: issue_labeled
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'labeled'
    steps:
      - name: Add Issue to Contribution Board
        if: github.event.label.name == 'good first issue' || github.event.label.name == 'help wanted'
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.CANVAS_BOARD_TOKEN }}
          organization: Workday
          project_id: 4
          resource_node_id: ${{ github.event.issue.node_id }}
          custom_field_values: '[{\"name\": \"Contributions\",\"type\": \"single_select\",\"value\": \"Yes\"}]'
      - name: Move Issue to ${{ env.in_review }}
        if: github.event.label.name == 'ready for review'
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.CANVAS_BOARD_TOKEN }}
          organization: Workday
          project_id: 4
          resource_node_id: $${{ github.event.issue.node_id }}
          status_value: ${{ env.in_review }}
  pr_opened:
    name: pr_opened
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Move release PR to ${{ env.in_review }}
        if: startsWith(github.head_ref, 'merge/prerelease/minor-into-prerelease/major')
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.CANVAS_BOARD_TOKEN }}
          organization: Workday
          project_id: 4
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.in_review }}
          custom_field_values: '[{\"name\": \"Priority\",\"type\": \"single_select\",\"value\": \"ğŸŒ‹ Urgent\"}]'
